#ifndef PHYSICSENGINE_H
#define PHYSICSENGINE_H

#include <vector>
#include <algorithm>
#include "Vector2d.h"
#include "Body.h"
#include "Collider.h"
#include "Config.h"

/// @brief Data structure holding infomation about a collision event.
/// Generated by collision detection functions and used in collision resolution.
struct CollisionManifold{
        bool isColliding; ///< True if a collision is occurring.
        Vector2d normal; ///< The direction vector along which the collision occurs.
        float depth; ///< Penetration depth of the collision, how much the objects overlap.
};


/// @brief The core physics simulation system.
/// Manages all physical bodies, handles the simulation loop,
/// computes forces, and detects and resolves collisions.
class PhysicsEngine {
    /// @brief Container for all physical bodies in the simulation.
    std::vector<Body*> bodies;

    /// @brief Internal buffer to store state of simulation for reseting.
    std::vector<Body*> savedState;

    /// @brief Widht of the simulation world boundaries.
    float simWidth;

    /// @brief Height of the simulation world boundaries.
    float simHeight;


    // --- Collision Logic ---

    /// @brief Handles collision between a body and the world boundaries.
    void handleWallCollision(Body* b);

    /// @brief Resolves collision between two bodies.
    /// @param m Collision manifold containing collision details.
    void handleCollision(Body* b1, Body* b2, const CollisionManifold& m);

    /// @brief Determines the shape types of b1 and b2 and calls the appropriate collision detection function.
    /// @return CollisionManifold containing collision details.
    CollisionManifold checkCollision(Body* b1, Body* b2);

    /// @brief Checks for collision between two circles.
    CollisionManifold interesectCircleCircle(Body* b1, Body* b2);

    /// @brief Checks for collision between a circle and a box.
    CollisionManifold interesectCircleBox(Body* circle, Body* box);

    /// @brief Checks for collision between two boxes.
    CollisionManifold intersectBoxBox(Body* b1, Body* b2);


    /// @brief Calculates and applies N-body gravitational and electrostatic forces between all bodies.
    /// Complexity: O(n^2)
    void applyNBodyForces();

public:
    /// @brief Constructor. Initializes simulation boundaries with default values.
    PhysicsEngine() : simWidth(800), simHeight(600) {}


    // --- Body Management ---

    /// @brief Adds a new Body to the simulation.
    void addBody(Body* body) {bodies.push_back(body);}

    /// @brief Removes a Body from the simulation.
    void removeBody(Body* body);

    /// @brief Removes all bodies from the simulation.
    void clearBodies();

    // --- Simulation Loop ---
    
    /// @brief Advances the simulation by one time step dt.
    /// 1. Applies global forces (Gravity downward).
    /// 2. Applies N-body forces (Gravity, Electrostatics).
    /// 3. Integrates motion (Updates positions and velocities).
    /// 4. Detects and resolves collisions (Body-Body, Body-Walls).
    /// @param dt Delta time (time step) in seconds.
    void update(float dt);

    // ---  Getters / Setters ---

    /// @brief Returns the std::vector of all bodies in the simulation.
    std::vector<Body*> getBodies() const {return bodies;}

    /// @brief Returns the dimensions of the simulation world boundaries.
    Vector2d getSimBounds() const {return {simWidth, simHeight};}

    /// @brief Sets the dimensions of the simulation world boundaries.
    void setSimBounds(float width, float height) {simWidth = width; simHeight = height;}

    /// @brief Finds a body at the given position.
    /// @param pos The point to check for a body (world coordinates).
    /// @return A pointer to the found body, or nullptr if no body is found at that position.
    Body* findBodyAt(Vector2d pos);
};

#endif